#' Add land-cover codes and classes to Mosquito Alert model inputs
#'
#' Loads the weather-enriched model-preparation dataset generated by
#' [add_weather_features()], extracts land-cover classes from the corresponding
#' raster, and writes a new `model_prep_*_wx_lc.Rds` file that appends both the
#' numeric code and descriptive class.
#'
#' @param dataset Either the in-memory weather-enriched dataset (output of
#'   [add_weather_features()]) or a path to the corresponding RDS file. When a
#'   data object is provided it must carry an `output_path` attribute naming the
#'   most recently saved file; the land-cover enriched output is written to
#'   `data_dir` with `_lc.Rds` appended to that stem when `write_output` is
#'   `TRUE`.
#' @param data_dir Directory holding the processed rasters and where the output
#'   dataset will be written. Defaults to `"data/proc"`.
#' @param verbose Logical; if `TRUE`, prints status messages while processing.
#' @param write_output Logical flag; when `TRUE` (default) the enriched dataset
#'   is written to disk. Set to `FALSE` to skip writing while still returning the
#'   augmented object and updating its metadata.
#'
#' @return A tibble/data frame containing the augmented dataset. Attributes
#'   from the input object are preserved, and two additional attributes are set:
#'   `landcover_source` (the raster path) and `output_path` (the saved file).
#' @export
#' @importFrom terra rast crs extract vect cats
#' @importFrom sf st_as_sf st_transform st_make_valid
add_landcover_features <- function(
  dataset,
  data_dir = "data/proc",
  verbose = TRUE,
  write_output = TRUE
) {
  infer_slug <- function(path) {
    fname <- basename(path)
    matches <- regexec("^model_prep_(.+?)_base", fname)
    parts <- regmatches(fname, matches)[[1]]
    if (length(parts) >= 2) parts[2] else NA_character_
  }

  dataset_is_path <- is.character(dataset) && length(dataset) == 1L
  if (dataset_is_path) {
    dataset_path <- dataset
    if (!file.exists(dataset_path)) {
      stop("Input dataset not found at ", dataset_path, call. = FALSE)
    }
    enriched <- readRDS(dataset_path)
  } else {
    enriched <- dataset
    dataset_path <- attr(enriched, "output_path", exact = TRUE)
    if (is.null(dataset_path) || !nzchar(dataset_path)) {
      stop(
        "Input dataset must carry an `output_path` attribute or be provided as a file path.",
        call. = FALSE
      )
    }
  }

  location_slug <- attr(enriched, "location_slug", exact = TRUE)
  if (is.null(location_slug) || !nzchar(location_slug)) {
    location_slug <- infer_slug(dataset_path)
  }
  if (is.na(location_slug) || !nzchar(location_slug)) {
    stop("Could not determine location slug from dataset; ensure it carries a `location_slug` attribute.", call. = FALSE)
  }
  attr(enriched, "location_slug") <- location_slug

  landcover_filename <- paste0("spatial_", location_slug, "_landcover.tif")
  landcover_path <- file.path(data_dir, landcover_filename)
  if (!file.exists(landcover_path)) {
    stop("Land-cover raster not found at ", landcover_path, call. = FALSE)
  }

  if (isTRUE(verbose)) {
    message("Using weather dataset from ", dataset_path)
  }
  base_attrs <- attributes(enriched)
  if (!all(c("lon", "lat") %in% names(enriched))) {
    stop("Weather dataset must contain `lon` and `lat` columns.", call. = FALSE)
  }

  valid_points <- stats::complete.cases(enriched[c("lon", "lat")])
  if (!any(valid_points)) {
    stop("No valid lon/lat coordinates available to extract land-cover values.", call. = FALSE)
  }

  if (isTRUE(verbose)) message("Loading land-cover raster from ", landcover_path)
  landcover_raster <- terra::rast(landcover_path)
  if (terra::nlyr(landcover_raster) > 1L) {
    warning("Land-cover raster has multiple bands; using the first band for extraction.")
  }

  # Extract the category table (ESA codes and labels) from the raster metadata
  category_table <- terra::cats(landcover_raster)[[1]]

  points_sf <- sf::st_as_sf(enriched[valid_points, ], coords = c("lon", "lat"), crs = 4326, remove = FALSE)
  points_sf <- sf::st_make_valid(points_sf)
  points_sf <- sf::st_transform(points_sf, terra::crs(landcover_raster))

  extracted <- terra::extract(landcover_raster, terra::vect(points_sf), ID = FALSE)
  if (ncol(extracted) == 0) {
    stop("No land-cover values were extracted; check coordinate reference systems.", call. = FALSE)
  }

  landcover_raw <- rep(NA_integer_, nrow(enriched))
  landcover_raw[valid_points] <- extracted[[1]]

  landcover_codes <- landcover_raw
  landcover_classes <- rep(NA_character_, nrow(enriched))

  if (!is.null(category_table) && nrow(category_table) > 0 && "value" %in% names(category_table)) {
    non_na_raw <- unique(landcover_raw[!is.na(landcover_raw)])
    if (!all(non_na_raw %in% category_table$value)) {
      id_lookup <- setNames(category_table$value, as.character(seq_len(nrow(category_table))))
      codes_mapped <- unname(id_lookup[as.character(landcover_raw)])
      landcover_codes <- codes_mapped
    }

    class_lookup <- setNames(as.character(category_table$class), as.character(category_table$value))
    landcover_classes <- unname(class_lookup[as.character(landcover_codes)])
  }

  enriched$landcover_code <- landcover_codes
  enriched$landcover_class <- landcover_classes
  enriched$presence <- FALSE
  enriched$presence[valid_points] <- TRUE

  stem <- tools::file_path_sans_ext(basename(dataset_path))
  output_filename <- paste0(stem, "_lc.Rds")
  output_path <- file.path(data_dir, output_filename)

  preserve <- base_attrs[setdiff(names(base_attrs), c("names", "row.names", "class"))]
  for (nm in names(preserve)) {
    attr(enriched, nm) <- preserve[[nm]]
  }

  attr(enriched, "landcover_source") <- landcover_path
  attr(enriched, "output_path") <- output_path
  attr(enriched, "location_slug") <- location_slug

  if (isTRUE(write_output)) {
    if (isTRUE(verbose)) message("Saving land-cover enriched dataset to ", output_path)
    dir.create(dirname(output_path), recursive = TRUE, showWarnings = FALSE)
    saveRDS(enriched, output_path)
  } else if (isTRUE(verbose)) {
    message("Land-cover features added (not written to disk).")
  }

  enriched
}




