#' Fit a baseline Mosquito Alert occupancy model with brms
#'
#' Reads the enriched Mosquito Alert modelling dataset (either from disk or an
#' in-memory data frame), prepares the predictors used in the baseline
#' specification, and fits a Bernoulli-response model using `brms`. The function
#' assumes the input was generated by the package's feature engineering
#' pipeline and therefore contains the required columns (e.g. `presence`,
#' `sea_days`, `maxTM`). The fitted model is returned invisibly and, by default,
#' also written to disk alongside the source dataset when a path is available.
#'
#' @param dataset Either an in-memory data frame or the path to the RDS file
#'   containing the model-preparation dataset.
#' @param priors Optional prior specification created with `brms::set_prior()`.
#'   Defaults to `NULL`, which uses the brms defaults.
#' @param nchains Number of MCMC chains to run. Defaults to 4.
#' @param threads_per_chain Number of within-chain threads (requires the
#'   `cmdstanr` backend). Defaults to 1 (single-threaded chains).
#' @param adapt_delta Target acceptance rate for the NUTS sampler. Defaults to
#'   0.99.
#' @param max_treedepth Maximum tree depth for the NUTS sampler. Defaults to 12.
#' @param backend Sampling backend passed to `brms::brm()`. Defaults to
#'   `"cmdstanr"` but `"rstan"` is supported as well.
#' @param write_output Logical; when `TRUE` the fitted model is saved to disk
#'   using the same directory and stem as `dataset_path` with a
#'   `_brms_model.Rds` suffix. Defaults to `TRUE`.
#' @param output_path Optional path where the fitted model should be written. If
#'   `NULL` (default) and `write_output` is `TRUE`, the path is auto-derived from
#'   `dataset_path`.
#' @param verbose Logical; if `TRUE`, progress messages are emitted. Defaults to
#'   `TRUE`.
#'
#' @return The fitted `brmsfit` object. The dataset used for modelling is stored
#'   in the `model_data` attribute and the saved path (if any) is stored in the
#'   `output_path` attribute.
#' @export
run_brms_model <- function(
  dataset,
  priors = NULL,
  nchains = 4,
  threads_per_chain = 1,
  adapt_delta = 0.99,
  max_treedepth = 12,
  backend = c("cmdstanr", "rstan"),
  write_output = TRUE,
  output_path = NULL,
  verbose = TRUE
) {
  backend <- match.arg(backend)

  if (!requireNamespace("brms", quietly = TRUE)) {
    stop("Package 'brms' must be installed to fit the model.", call. = FALSE)
  }
  if (identical(backend, "cmdstanr") && !requireNamespace("cmdstanr", quietly = TRUE)) {
    stop("Backend 'cmdstanr' selected but package 'cmdstanr' is not installed.", call. = FALSE)
  }

  if (!is.numeric(nchains) || length(nchains) != 1L || is.na(nchains) || nchains < 1) {
    stop("`nchains` must be a positive numeric scalar.", call. = FALSE)
  }
  nchains <- as.integer(nchains)

  if (!is.numeric(threads_per_chain) || length(threads_per_chain) != 1L ||
      is.na(threads_per_chain) || threads_per_chain < 1) {
    stop("`threads_per_chain` must be a positive numeric scalar.", call. = FALSE)
  }
  threads_per_chain <- as.integer(threads_per_chain)

  if (!is.numeric(adapt_delta) || length(adapt_delta) != 1L ||
      is.na(adapt_delta) || adapt_delta <= 0 || adapt_delta >= 1) {
    stop("`adapt_delta` must be a numeric value between 0 and 1.", call. = FALSE)
  }
  if (!is.numeric(max_treedepth) || length(max_treedepth) != 1L ||
      is.na(max_treedepth) || max_treedepth < 1) {
    stop("`max_treedepth` must be a positive numeric scalar.", call. = FALSE)
  }

  dataset_is_path <- is.character(dataset) && length(dataset) == 1L && nzchar(dataset)
  dataset_path <- NULL

  if (dataset_is_path) {
    dataset_path <- dataset
    if (!file.exists(dataset_path)) {
      stop("Dataset not found at ", dataset_path, call. = FALSE)
    }
    dataset <- readRDS(dataset_path)
  }

  if (!is.data.frame(dataset)) {
    stop("`dataset` must be a data frame or a path to an RDS file containing one.",
         call. = FALSE)
  }

  required_cols <- c(
    "date", "grid_id", "grid_lon", "grid_lat", "tigacell_lon", "tigacell_lat",
    "TigacellID", "TigacellID_small", "sea_days", "biweek", "presence", "year",
    "ndvi_distance_m", "ndvi_value_nearest", "ndvi_ddf_proximity", "elevation_m",
    "popdensity_km2", "landcover_code", "landcover_class", "mwi", "maxTM", "meanPPT24H"
  )
  missing_cols <- setdiff(required_cols, names(dataset))
  if (length(missing_cols) > 0) {
    stop(
      "Dataset is missing required columns: ",
      paste(missing_cols, collapse = ", "),
      call. = FALSE
    )
  }

  model_cols <- unique(required_cols)
  model_data <- dataset[, model_cols, drop = FALSE]

  model_data$year <- factor(model_data$year)
  model_data$landcover_code <- factor(model_data$landcover_code)
  suppressWarnings({
    model_data$maxTM_z <- as.numeric(scale(model_data$maxTM))
    model_data$ppt_z <- as.numeric(scale(log1p(model_data$meanPPT24H)))
    model_data$ndvi_z <- as.numeric(scale(model_data$ndvi_ddf_proximity))
    model_data$elev_z <- as.numeric(scale(model_data$elevation_m))
    model_data$pop_z <- as.numeric(scale(log1p(model_data$popdensity_km2)))
  })

  thread_arg <- NULL
  if (threads_per_chain > 1) {
    thread_arg <- brms::threading(threads_per_chain)
  }

  if (isTRUE(verbose)) {
    message(
      "Fitting brms model with ", nchains, " chain(s) using backend '", backend, "'."
    )
  }

  model_fit <- brms::brm(
    presence ~ brms::s(sea_days, bs = "cc", k = 12) +
      brms::s(maxTM_z, k = 6) +
      ppt_z + ndvi_z + elev_z + pop_z +
      (1 | year) + (1 | landcover_code),
    data = model_data,
    family = brms::bernoulli(),
    backend = backend,
    chains = nchains,
    cores = nchains,
    threads = thread_arg,
    prior = priors,
    control = list(adapt_delta = adapt_delta, max_treedepth = max_treedepth)
  )

  attr(model_fit, "model_data") <- model_data
  if (!is.null(dataset_path)) {
    attr(model_fit, "source_dataset") <- dataset_path
  }

  if (isTRUE(write_output)) {
    if (is.null(output_path) || !nzchar(output_path)) {
      if (is.null(dataset_path)) {
        stop("`write_output = TRUE` requires `dataset` to be a file path or `output_path` to be supplied.",
             call. = FALSE)
      }
      stem <- tools::file_path_sans_ext(basename(dataset_path))
      output_path <- file.path(dirname(dataset_path), paste0(stem, "_brms_model.Rds"))
    }
    dir.create(dirname(output_path), recursive = TRUE, showWarnings = FALSE)
    saveRDS(model_fit, output_path)
    attr(model_fit, "output_path") <- output_path
    if (isTRUE(verbose)) {
      message("brms model saved to ", output_path)
    }
  } else if (!is.null(output_path)) {
    warning("`output_path` was supplied but `write_output` is FALSE; nothing was written.",
            call. = FALSE)
  }

  model_fit
}